/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.financeiro.contaspagar.entity.contapagarmultiple;


import java.util.HashMap;
import java.util.Map;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

		
@ApiModel(description = "Details about list filter of Registros de pagamento")
public class ContaPagarMultipleListFilter {

	@ApiModelProperty(notes = "Conta a pagar pai", position = 11)
	private java.util.UUID contaPagarId;
	
	@ApiModelProperty(notes = "Id da conciliação bancária is not null", position = 12)
	private Boolean idConcBancariaIsNotNull;
	
	@ApiModelProperty(notes = "Histórico da conciliação bancária", position = 13)
	private java.util.List<String> histConcBancaria;
	
	// Map field for developer customizing parameters.
	@ApiModelProperty(notes = "Campo tipo mapa (chave = valor) onde o desenvolvedor pode passar seus parâmetros personalizados no formato objeto JSON.", position = 9999)
	private Map<Object, Object> customParams = new HashMap<>();
	
	public java.util.UUID getContaPagarId() {
		return contaPagarId;
	}
			
	public void setContaPagarId(java.util.UUID contaPagarId) {
		this.contaPagarId = contaPagarId;
	}
	
	public Boolean isIdConcBancariaIsNotNull() {
		return idConcBancariaIsNotNull != null && idConcBancariaIsNotNull;
	}
	
	public Boolean getIdConcBancariaIsNotNull() {
		return idConcBancariaIsNotNull;
	}
			
	public void setIdConcBancariaIsNotNull(Boolean idConcBancariaIsNotNull) {
		this.idConcBancariaIsNotNull = idConcBancariaIsNotNull;
	}
	
	public java.util.List<String> getHistConcBancaria() {
		return histConcBancaria;
	}
	
	public void setHistConcBancaria(java.util.List<String> histConcBancaria) {
		this.histConcBancaria = histConcBancaria;
	}
	
	public Map<Object, Object> getCustomParams() {
		return customParams;
	}
	
	public void setCustomParams(Map<Object, Object> customParams) {
		this.customParams = customParams;
	}
	
}
