/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.financeiro.contaspagar.entity.contapagarmultiple;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
		
@ApiModel(description = "Details about sums of Registros de pagamento")
public class ContaPagarMultipleSumFields {
	
	@ApiModelProperty(notes = "Sum of Valor", required = true, position = 2)
	private java.math.BigDecimal sumValorPago;
	
	public ContaPagarMultipleSumFields() {
		// Contructor for reflexion, injection, Jackson, QueryDSL, etc proposal.
	}
	
	public java.math.BigDecimal getSumValorPago() {
		return sumValorPago;
	}
	
	public void setSumValorPago(java.math.BigDecimal sumValorPago) {
		this.sumValorPago = sumValorPago;
	}

}
