/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.financeiro.contaspagar.entity.contapagarmultiple;



public interface ContaPagarMultipleAutoComplete {

	java.util.UUID getId();
	
	String getDescricao();
	
	void setId(java.util.UUID id);
	
	void setDescricao(String descricao);

}
