/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/


package br.com.kerubin.api.financeiro.contaspagar.entity.contapagarmultiple;

import javax.inject.Inject;
import org.springframework.stereotype.Component;
import br.com.kerubin.api.servicecore.mapper.ObjectMapper;

@Component
public class ContaPagarMultipleDTOConverter {

	@Inject
	private ObjectMapper mapper;

	public ContaPagarMultiple convertEntityToDto(ContaPagarMultipleEntity entity) {
		ContaPagarMultiple dto = null;
		if (entity != null) {
			dto = mapper.map(entity, ContaPagarMultiple.class, true); // Do not permit passwords fields go outside.
		}
		return dto;
	}


	public ContaPagarMultipleEntity convertDtoToEntity(ContaPagarMultiple dto) {
		ContaPagarMultipleEntity entity = null;
		if (dto != null) {
			entity = mapper.map(dto, ContaPagarMultipleEntity.class);
		}
		return entity;
	}


}