/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.financeiro.contaspagar.messaging;

import java.text.MessageFormat;

import javax.inject.Inject;

import org.springframework.amqp.AmqpRejectAndDontRequeueException;
import org.springframework.amqp.rabbit.annotation.RabbitListener;
import org.springframework.stereotype.Service;

import br.com.kerubin.api.messaging.core.DomainMessage;
import lombok.extern.slf4j.Slf4j;

/**
 * Starts handling all received messages from RabbitMQ for the queue financeiroContasPagarQueue.
 * WARNING: The FinanceiroContasPagarEventHandler interface must be implemented by the implementation module.
 * */
@Slf4j
@Service
public class FinanceiroContasPagarListenerEventHandler {
	
	@Inject
	private FinanceiroContasPagarEventHandler financeiroContasPagarEventHandler;
	
	@RabbitListener(queues = "#{financeiroContasPagarQueue.name}")
	public void onHandleEventListener(DomainMessage message) {
		log.info("Handling event listener received message from broker RabbitMQ: {}", message);
		try {
			financeiroContasPagarEventHandler.handleEvent(message);
		} catch(Exception e) {
			log.error(MessageFormat.format("Error: {0}, handling message: {1}", e.getMessage(), message), e);
			throw new AmqpRejectAndDontRequeueException(e);
		}
	}
	
}

