/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.financeiro.contaspagar;

public interface FinanceiroContasPagarConstants {
	
	String DOMAIN = "financeiro";
	String SERVICE = "contas_pagar";
	
	interface Events {
		
	}

}
