/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.financeiro.contaspagar;


import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


		
@ApiModel(description = "Details about Tipo da receita/despesa")
public enum TipoReceitaDespesa {
	@ApiModelProperty(notes = "Variável")
	VARIAVEL,
	
	@ApiModelProperty(notes = "Fixa")
	FIXO;
}

