/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.financeiro.contaspagar;


import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


		
@ApiModel(description = "Details about Tipo do pagamento")
public enum TipoPagamentoConta {
	@ApiModelProperty(notes = "Pagamento único")
	SINGLE,
	
	@ApiModelProperty(notes = "Pagamentos múltiplos")
	MULTIPLE;
}

